@extends('layouts.app')
@section('content')
<div class="role-page"><div class="role-hero"><div class="role-hero-copy"><span class="role-kicker">Akun</span><h3>Profil Saya</h3><p>Perbarui email dan kata sandi akun Anda.</p></div></div>
<div class="alert alert-info mt-3"><button id="enablePush" class="btn btn-sm btn-outline-primary" type="button">Aktifkan Notifikasi Perangkat</button><span class="ms-2">Izinkan notifikasi agar aktivitas penting tampil walau browser ditutup.</span></div>
<div class="row g-3"><div class="col-lg-6"><section class="role-table-card p-4"><h5>Data Akun</h5><form method="post" action="{{ route('profile.update') }}">@csrf @method('PUT')<label class="form-label mt-3">Nama</label><input class="form-control" name="name" value="{{ old('name',$user->name) }}" required><label class="form-label mt-3">Email</label><input class="form-control" type="email" name="email" value="{{ old('email',$user->email) }}" required>@if(in_array($user->role, ['kepala_sekolah', 'wali_kelas'], true))<label class="form-label mt-3">NIP</label><input class="form-control" name="nip" value="{{ old('nip',$user->nip) }}" maxlength="50" required><small class="text-muted">NIP ini dikelola oleh akun Anda sendiri.</small>@endif<button class="btn btn-primary mt-3">Simpan Profil</button></form></section></div>
<div class="col-lg-6"><section class="role-table-card p-4"><h5>Ganti Kata Sandi</h5><form method="post" action="{{ route('profile.password') }}">@csrf @method('PUT')<label class="form-label mt-3">Kata sandi saat ini</label><input class="form-control" type="password" name="current_password" required><label class="form-label mt-3">Kata sandi baru</label><input class="form-control" type="password" name="password" minlength="8" required><label class="form-label mt-3">Ulangi kata sandi baru</label><input class="form-control" type="password" name="password_confirmation" minlength="8" required><button class="btn btn-primary mt-3">Ganti Kata Sandi</button></form></section></div></div></div>
@endsection
@push('scripts')
<script>
document.getElementById('enablePush')?.addEventListener('click', async () => { try { const permission = await Notification.requestPermission(); if (permission !== 'granted') return; const registration = await navigator.serviceWorker.ready; const key = '{{ config('services.webpush.public_key') }}'; if (!key) return alert('VAPID key belum dikonfigurasi server.'); const bytes = Uint8Array.from(atob(key.replace(/-/g,'+').replace(/_/g,'/')), c => c.charCodeAt(0)); const sub = await registration.pushManager.subscribe({userVisibleOnly:true, applicationServerKey:bytes}); await fetch('{{ route('push-subscriptions.store') }}', {method:'POST', headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'}, body:JSON.stringify(sub.toJSON())}); alert('Notifikasi perangkat aktif.'); } catch(e) { alert('Notifikasi belum dapat diaktifkan. Pastikan situs memakai HTTPS.'); } });
</script>
@endpush
